source 'https://gitlab.com/inavi_us/inavi-pod-repo.git'

target 'Full Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'YolbilMobileSDK'
  pod 'INVSensorManager'
  pod 'INVPositioner' 
  pod 'INVRouting'
  pod 'INVManifest'
  pod 'INVNotificationService'
end
