source 'https://gitlab.com/inavi_us/inavi-pod-repo.git'

target 'NotificationService Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'INVNotificationService'
end
